package edu.memphis.ccrg.lida.framework.gui.events;

import edu.memphis.ccrg.lida.framework.ModuleType;

/**
 * Event generated by the framework to be handled by the GUI.
 * 
 * @author Javier snaider
 * 
 */
public class FrameworkGuiEvent {

	private ModuleType module;
	private String message;
	private Object data;

	/**
	 * @param moduleId
	 * @param message
	 * @param data
	 */
	public FrameworkGuiEvent(ModuleType m, String message, Object data) {
		this.module = m;
		this.message = message;
		this.data = data;
	}

	public void setModule(ModuleType m){
		module = m;
	}
	/**
	 * @return the moduleId
	 */
	public ModuleType getModule() {
		return module;
	}

	public void setMessage(String m){
		message = m;
	}
	/**
	 * @return the message
	 */
	public String getMessage() {
		return message;
	}

	public void setData(Object o){
		data = o;
	}
	/**
	 * @return the data
	 */
	public Object getData() {
		return data;
	}
}
