package implementation.ryan.gui;

import implementation.ryan.main.Start;

import java.util.HashMap;
import java.util.Map;
import edu.memphis.ccrg.lida.perception.PerceptualAssociativeMemoryImpl;
import edu.memphis.ccrg.lida.util.FrameworkTimer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContactEditorUI.java
 *
 * Created on Mar 10, 2009, 12:54:05 AM
 */

/**
 *
 * @author ryanjmccall
 */
public class ControlGui extends javax.swing.JFrame {
	
	private static final long serialVersionUID = 1L;
	private FrameworkTimer timer;
	private Start motherThread;
	private PerceptualAssociativeMemoryImpl pam;
	boolean isPaused = true;

    /** Creates new form ContactEditorUI 
     * @param start 
     * @param timer 
     * @param pam */
    public ControlGui(FrameworkTimer timer, Start start, PerceptualAssociativeMemoryImpl pam) {
    	this.timer = timer;
    	isPaused = timer.getStartStatus();
    	motherThread = start;
    	this.pam = pam;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        startPauseButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        nextStepButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pamSelectivityTextField = new javax.swing.JTextField();
        setSelectivityButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        setUpscaleButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        threadCountTextField = new javax.swing.JTextField();
        linkCountTextField = new javax.swing.JTextField();
        upscaleTextField = new javax.swing.JTextField();
        nodeCountTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        startPauseButton.setText("Start/Pause");
        startPauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPauseButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        nextStepButton.setText("Next Step");
        nextStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStepButtonClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel1.setText("LIDA Control Panel");

        jLabel2.setText("PAM Selectivity");

        pamSelectivityTextField.setText("NA");

        setSelectivityButton.setText("Set");
        setSelectivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSelectivityButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("PAM Upscale");

        setUpscaleButton.setText("Set");
        setUpscaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setUpscaleClicked(evt);
            }
        });

        jLabel4.setText("Thread Count");

        jLabel5.setText("Node Count");

        jLabel6.setText("Link Count");

        jLabel7.setText("Thread Status");

        statusLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        if(isPaused)
        	statusLabel.setText("LIDA is PAUSED");
        else
        	statusLabel.setText("LIDA is RUNNING");

        threadCountTextField.setText("--");

        linkCountTextField.setText("--");

        upscaleTextField.setText("NA");

        nodeCountTextField.setText("--");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel7)
                            .add(jLabel3)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel2))
                        .add(20, 20, 20))
                    .add(layout.createSequentialGroup()
                        .add(nextStepButton)
                        .add(18, 18, 18)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(startPauseButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 42, Short.MAX_VALUE)
                        .add(quitButton)
                        .add(39, 39, 39))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(statusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(nodeCountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(pamSelectivityTextField)
                                    .add(upscaleTextField))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(setUpscaleButton)
                                    .add(setSelectivityButton)))
                            .add(linkCountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(threadCountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(126, Short.MAX_VALUE))))
            .add(layout.createSequentialGroup()
                .add(119, 119, 119)
                .add(jLabel1)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(nodeCountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(linkCountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(threadCountTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(upscaleTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(setUpscaleButton))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pamSelectivityTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(setSelectivityButton)
                    .add(jLabel2))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(statusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nextStepButton)
                    .add(startPauseButton)
                    .add(quitButton))
                .add(46, 46, 46))
        );

        pack();
    }// </editor-fold>

    
    public void refreshGuiValues(){
    	nodeCountTextField.setText(pam.getNodeCount() + "");
    	linkCountTextField.setText(pam.getLinkCount() + "");
    	pamSelectivityTextField.setText(pam.getSelectivity() + "");
    	threadCountTextField.setText(motherThread.getThreadCount() + "");
    	upscaleTextField.setText(pam.getUpscale() + "");
    }

    private void setSelectivityButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	String s = pamSelectivityTextField.getText();
    	double selectivity = -1.0;
    	try{ 
    		selectivity = Double.parseDouble(s); 
    	}catch(Exception e){ 
    		System.out.println("Bad selectivity input." + e);
    	}
    	Map<String, Object> params = new HashMap<String, Object>();
    	if(selectivity != -1.0)
    		params.put("selectivity", selectivity);
    	
    	pam.setParameters(params); 
    	refreshGuiValues();
    }

    private void setUpscaleClicked(java.awt.event.ActionEvent evt) {
    	String s = upscaleTextField.getText();
    	double upscale = -1.0;
    	try{ 
    		upscale = Double.parseDouble(s); 
    	}catch(Exception e){ 
    		System.out.println("Bad upscale input." + e);
    	}
    	Map<String, Object> params = new HashMap<String, Object>();
    	if(upscale != -1.0)
    		params.put("upscale", upscale);
    	
    	pam.setParameters(params);  
    	refreshGuiValues();
    }
   
    private void startPauseButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	refreshGuiValues();
    	
    	isPaused = !isPaused;
		if(isPaused)
			statusLabel.setText("LIDA is PAUSED");
		else
			statusLabel.setText("LIDA is RUNNING");
		timer.toggleRunningThreads();
    }
    
    private void nextStepButtonClicked(java.awt.event.ActionEvent evt) {
    	refreshGuiValues();
        timer.haveThreadRunOnceThenPause();
    }
    
    /**
     * Ensures threads print out their cycle times even if they were paused.
     * Tells the main thread to end all child threads.
     * Pauses giving the children time to shutdown.
     * Finally, terminates everything.
     * 
     * @param evt
     */
    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	statusLabel.setText("LIDA is QUITTING");
		timer.resumeRunningThreads(); 
		motherThread.stopThreads();
		try{Thread.sleep(1000);}catch(Exception e2){}
		System.exit(0);
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField linkCountTextField;
    private javax.swing.JButton nextStepButton;
    private javax.swing.JTextField nodeCountTextField;
    private javax.swing.JTextField pamSelectivityTextField;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton setSelectivityButton;
    private javax.swing.JButton setUpscaleButton;
    private javax.swing.JButton startPauseButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField threadCountTextField;
    private javax.swing.JTextField upscaleTextField;
    // End of variables declaration

}
