/**
 * 
 */
package edu.memphis.ccrg.lida.globalworkspace;

/**
 * Input Data to GW.
 * It is generated by Attention Codeletes.
 * Coalitions must overwrite correctly equals() and hashcode() methods
 * 
 *  * @author Javier Snaider
 
 */
public interface Coalition { 

	public double getActivation();
	
	/**
	 * 
	 * @return The Content of the coalition.
	 */
	public BroadcastContent getContent();
	
	/**
	 * this method decay the activation of the coalition. It should be called after
	 * each broadcast by the GlobalWorkspace
	 */
	public void decay(long ticks);
	
	public void updateActivation();
}
