/**
 * 
 */
package edu.memphis.ccrg.lida.globalworkspace;

import edu.memphis.ccrg.lida.workspace.currentSituationalModel.CurrentSituationalModelContent;

/**
 * Input Data to GW.
 * It is generated by Attention Codeletes.
 * Coalitions must overwrite correctly equals() and hashcode() methods
 * 
 *  * @author Javier Snaider
 
 */
public interface Coalition {
	/**
	 * 
	 * @return the total activation of the coalition.
	 */
	public double getActivation();
	/**
	 * 
	 * @return The Content of the coalition.
	 */
	public CurrentSituationalModelContent getContent();
	
	/**
	 * this method decay the activation of the coalition. It should be called after
	 * each broadcast by the GlobalWorkspace
	 */
	public void decay();
}
