/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestGui.java
 *
 * Created on Apr 3, 2009, 12:07:29 PM
 */

package edu.memphis.ccrg.lida.example.genericLIDA.gui;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author ryanjmccall
 */
public class NodeLinkFlowGui extends javax.swing.JFrame{
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = 1L;
//	private Map<Integer, List<javax.swing.JTextField>> map = new HashMap<Integer, List<javax.swing.JTextField>>();
//	
//	public NodeLinkFlowGui(){
//	    initComponents();
//	    
//	    List<javax.swing.JTextField> fields = new ArrayList<javax.swing.JTextField>();
//    	fields.add(perceptNodes);
//    	fields.add(perceptLinks);
//    	map.put(FROM_PAM, fields);
//    	//
//    	List<javax.swing.JTextField> fields1 = new ArrayList<javax.swing.JTextField>();
//    	fields1.add(dmNodes);
//    	fields1.add(dmLinks);
//    	map.put(FROM_DM, fields1);
//    	//
//    	List<javax.swing.JTextField> fields2 = new ArrayList<javax.swing.JTextField>();
//    	fields2.add(temNodes);
//    	fields2.add(temLinks);
//    	map.put(FROM_TEM, fields2);
//    	//
//    	List<javax.swing.JTextField> fields3 = new ArrayList<javax.swing.JTextField>();
//    	fields3.add(pBufferNodes);
//    	fields3.add(pBufferLinks);
//    	map.put(FROM_PERCEPTUAL_BUFFER, fields3);
//    	//
//    	List<javax.swing.JTextField> fields4 = new ArrayList<javax.swing.JTextField>();
//    	fields4.add(eBufferNodes);
//    	fields4.add(eBufferLinks);
//    	map.put(FROM_EPISODIC_BUFFER, fields4);
//    	//
//    	List<javax.swing.JTextField> fields5 = new ArrayList<javax.swing.JTextField>();
//    	fields5.add(bBufferNodes);
//    	fields5.add(bBufferLinks);
//    	map.put(FROM_BROADCAST_QUEUE, fields5);
//    	//
//    	List<javax.swing.JTextField> fields6 = new ArrayList<javax.swing.JTextField>();
//    	fields6.add(csmNodes);
//    	fields6.add(csmLinks);
//    	map.put(FROM_CSM, fields6);
//    	//
//    	List<javax.swing.JTextField> fields7 = new ArrayList<javax.swing.JTextField>();
//    	fields7.add(codeletsNodes);
//    	fields7.add(codeletsLinks);
//    	map.put(FROM_SBCODELETS, fields7);
//    	//
//    	List<javax.swing.JTextField> fields8 = new ArrayList<javax.swing.JTextField>();
//    	fields8.add(globalNodes);
//    	fields8.add(globalLinks);
//    	map.put(FROM_GLOBAL_WORKSPACE, fields8);
//    	//
//    	List<javax.swing.JTextField> fields9 = new ArrayList<javax.swing.JTextField>();
//    	fields9.add(proceduralNodes);
//    	fields9.add(proceduralLinks);
//    	map.put(FROM_PROCEDURAL_MEMORY, fields9);
//    	//
//    	List<javax.swing.JTextField> fields10 = new ArrayList<javax.swing.JTextField>();
//    	fields10.add(actionNodes);
//    	fields10.add(actionLinks);
//    	map.put(FROM_ACTION_SELECTION, fields10);
//	}//
//
//	/** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        pBufferNodes = new javax.swing.JTextField();
//        pBufferLinks = new javax.swing.JTextField();
//        jLabel4 = new javax.swing.JLabel();
//        codeletsLinks = new javax.swing.JTextField();
//        jLabel5 = new javax.swing.JLabel();
//        codeletsNodes = new javax.swing.JTextField();
//        csmLinks = new javax.swing.JTextField();
//        jLabel6 = new javax.swing.JLabel();
//        csmNodes = new javax.swing.JTextField();
//        jLabel9 = new javax.swing.JLabel();
//        jLabel10 = new javax.swing.JLabel();
//        jLabel11 = new javax.swing.JLabel();
//        globalNodes = new javax.swing.JTextField();
//        proceduralNodes = new javax.swing.JTextField();
//        globalLinks = new javax.swing.JTextField();
//        proceduralLinks = new javax.swing.JTextField();
//        actionLinks = new javax.swing.JTextField();
//        actionNodes = new javax.swing.JTextField();
//        jLabel12 = new javax.swing.JLabel();
//        jLabel13 = new javax.swing.JLabel();
//        eBufferNodes = new javax.swing.JTextField();
//        eBufferLinks = new javax.swing.JTextField();
//        jLabel14 = new javax.swing.JLabel();
//        bBufferNodes = new javax.swing.JTextField();
//        bBufferLinks = new javax.swing.JTextField();
//        jLabel15 = new javax.swing.JLabel();
//        temNodes = new javax.swing.JTextField();
//        temLinks = new javax.swing.JTextField();
//        jLabel16 = new javax.swing.JLabel();
//        dmNodes = new javax.swing.JTextField();
//        dmLinks = new javax.swing.JTextField();
//        perceptNodes = new javax.swing.JTextField();
//        perceptLinks = new javax.swing.JTextField();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jLabel1.setText("Percept");
//
//        jLabel2.setText("Nodes");
//
//        jLabel3.setText("Links");
//
//        pBufferNodes.setText("---");
//
//        pBufferLinks.setText("---");
//
//        jLabel4.setText("PerceptBuff");
//
//        codeletsLinks.setText("---");
//
//        jLabel5.setText("Codelets");
//
//        codeletsNodes.setText("---");
//
//        csmLinks.setText("---");
//
//        jLabel6.setText("CSM");
//
//        csmNodes.setText("---");
//
//        jLabel9.setText("Global Wk");
//
//        jLabel10.setText("Proced Mem");
//
//        jLabel11.setText("ActionSelect");
//
//        globalNodes.setText("---");
//
//        proceduralNodes.setText("---");
//
//        globalLinks.setText("---");
//
//        proceduralLinks.setText("---");
//
//        actionLinks.setText("---");
//
//        actionNodes.setText("---");
//
//        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 15));
//        jLabel12.setText("Node & Link Flow");
//
//        jLabel13.setText("EpisodicBuff");
//
//        eBufferNodes.setText("---");
//
//        eBufferLinks.setText("---");
//
//        jLabel14.setText("BroadcastBuff");
//
//        bBufferNodes.setText("---");
//
//        bBufferLinks.setText("---");
//
//        jLabel15.setText("TEM");
//
//        temNodes.setText("---");
//
//        temLinks.setText("---");
//
//        jLabel16.setText("DM");
//
//        dmNodes.setText("---");
//
//        dmLinks.setText("---");
//
//        perceptNodes.setText("---");
//
//        perceptLinks.setText("---");
//
//        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                    .add(jLabel2)
//                    .add(layout.createSequentialGroup()
//                        .add(jLabel3)
//                        .add(6, 6, 6)))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(layout.createSequentialGroup()
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(jLabel1)
//                            .add(perceptNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(jLabel4)
//                            .add(pBufferNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//                    .add(layout.createSequentialGroup()
//                        .add(perceptLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                        .add(18, 18, 18)
//                        .add(pBufferLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                    .add(layout.createSequentialGroup()
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(jLabel5)
//                            .add(codeletsLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(codeletsNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(csmLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(csmNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(jLabel6))))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(layout.createSequentialGroup()
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(temNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(temLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(jLabel15))
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(jLabel16)
//                            .add(dmNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(dmLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(eBufferNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(eBufferLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                                .add(jLabel13)
//                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                                        .add(proceduralLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                                        .add(proceduralNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                                    .add(jLabel10)))))
//                    .add(jLabel9)
//                    .add(globalNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                    .add(globalLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                        .add(bBufferLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                        .add(layout.createSequentialGroup()
//                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                                .add(jLabel14)
//                                .add(bBufferNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                            .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                    .add(layout.createSequentialGroup()
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(jLabel11)
//                            .add(actionNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .add(actionLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                        .addContainerGap())))
//            .add(layout.createSequentialGroup()
//                .add(173, 173, 173)
//                .add(jLabel12)
//                .addContainerGap(167, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//            .add(layout.createSequentialGroup()
//                .add(jLabel12)
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
//                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                        .add(layout.createSequentialGroup()
//                            .add(jLabel16)
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(dmNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(dmLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                        .add(layout.createSequentialGroup()
//                            .add(24, 24, 24)
//                            .add(temNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(temLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                        .add(jLabel15)
//                        .add(layout.createSequentialGroup()
//                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                                .add(jLabel4)
//                                .add(jLabel1))
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                                .add(jLabel2)
//                                .add(pBufferNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                                .add(perceptNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                                .add(jLabel3)
//                                .add(pBufferLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                                .add(perceptLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
//                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                        .add(layout.createSequentialGroup()
//                            .add(jLabel14)
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(bBufferNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(bBufferLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                        .add(layout.createSequentialGroup()
//                            .add(jLabel13)
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(eBufferNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                            .add(eBufferLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
//                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                    .add(layout.createSequentialGroup()
//                        .add(jLabel11)
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(actionNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(actionLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                    .add(layout.createSequentialGroup()
//                        .add(jLabel9)
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(globalNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(globalLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                    .add(layout.createSequentialGroup()
//                        .add(jLabel10)
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(layout.createSequentialGroup()
//                                .add(34, 34, 34)
//                                .add(proceduralLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                            .add(proceduralNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//                    .add(layout.createSequentialGroup()
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
//                            .add(jLabel5)
//                            .add(jLabel6))
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//                            .add(layout.createSequentialGroup()
//                                .add(csmNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                                .add(csmLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
//                            .add(layout.createSequentialGroup()
//                                .add(codeletsNodes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
//                                .add(codeletsLinks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
//                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
//                .add(10, 10, 10))
//        );
//    
//        pack();
//    }// </editor-fold>
//	
//    /**
//     * Check to make sure 'content' has at least 2 values.
//     * Get the textfields for the specified 'lidaComponent'
//     * If fields are found, then set them both with the values of 'content' 
//     */
//    public void receiveGuiContent(int lidaComponent, List<Object> content) {
//		if(content != null && content.size() > 1){
//			List<javax.swing.JTextField> fields = map.get(lidaComponent);
//			
//			if(fields != null){
//				fields.get(0).setText(content.get(0) + "");
//				fields.get(1).setText(content.get(1) + "");
//			}//
//		}//if 
//	}//method
//    
// // Variables declaration - do not modify
//    private javax.swing.JTextField actionLinks;
//    private javax.swing.JTextField actionNodes;
//    private javax.swing.JTextField bBufferLinks;
//    private javax.swing.JTextField bBufferNodes;
//    private javax.swing.JTextField codeletsLinks;
//    private javax.swing.JTextField codeletsNodes;
//    private javax.swing.JTextField csmLinks;
//    private javax.swing.JTextField csmNodes;
//    private javax.swing.JTextField dmLinks;
//    private javax.swing.JTextField dmNodes;
//    private javax.swing.JTextField eBufferLinks;
//    private javax.swing.JTextField eBufferNodes;
//    private javax.swing.JTextField globalLinks;
//    private javax.swing.JTextField globalNodes;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel10;
//    private javax.swing.JLabel jLabel11;
//    private javax.swing.JLabel jLabel12;
//    private javax.swing.JLabel jLabel13;
//    private javax.swing.JLabel jLabel14;
//    private javax.swing.JLabel jLabel15;
//    private javax.swing.JLabel jLabel16;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JTextField pBufferLinks;
//    private javax.swing.JTextField pBufferNodes;
//    private javax.swing.JTextField perceptLinks;
//    private javax.swing.JTextField perceptNodes;
//    private javax.swing.JTextField proceduralLinks;
//    private javax.swing.JTextField proceduralNodes;
//    private javax.swing.JTextField temLinks;
//    private javax.swing.JTextField temNodes;
//    // End of variables declaration

}//TestGui