create table app.lida (
    ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR(255)
);

create table app.actionselection (
    ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    LIDAID INTEGER,
    SERIALIZEDDATA BLOB
);

create table app.perceptualassociativememory (
    ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    LIDAID INTEGER,
    SERIALIZEDDATA BLOB
);

create table app.proceduralmemory (
    ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    LIDAID INTEGER,
    SERIALIZEDDATA BLOB
);

create table app.sensorymemory (
    ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    LIDAID INTEGER,
    SERIALIZEDDATA BLOB
);

create table app.tem_addresses (
    ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    LIDAID INTEGER,
    ADDRESS BLOB
);

create table app.tem_counters (
    ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ADDRESSID INTEGER,
    COUNTER BLOB
);

delete from app.lida;
delete from app.actionselection;
delete from app.perceptualassociativememory;
delete from app.proceduralmemory;
delete from app.sensorymemory;
delete from app.tem_addresses;
delete from app.tem_counters;