/*******************************************************************************
 * Copyright (c) 2009, 2010 The University of Memphis.  All rights reserved. 
 * This program and the accompanying materials are made available 
 * under the terms of the LIDA Software Framework Non-Commercial License v1.0 
 * which accompanies this distribution, and is available at
 * http://ccrg.cs.memphis.edu/assets/papers/2010/LIDA-framework-non-commercial-v1.0.pdf
 *******************************************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PropertiesPanel.java 
 *
 * Created on 14/08/2009, 13:37:17
 */
package edu.memphis.ccrg.lida.framework.gui.panels;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

import edu.memphis.ccrg.lida.framework.tasks.LidaTask;
import edu.memphis.ccrg.lida.framework.tasks.LidaTaskManager;

/**
 * 
 * @author Javier Snaider
 */
public class TaskQueuePanel extends LidaPanelImpl {

	private static final long serialVersionUID = 3129545758505110771L;
	private static final Logger logger = Logger
			.getLogger(TaskQueuePanel.class.getCanonicalName());
	private Map<Long, Queue<LidaTask>> tasks= new HashMap<Long, Queue<LidaTask>>();

	// private LidaTask[] taskArray;

	public TaskQueuePanel() {
		initComponents();
		//tasks = new HashMap<Long, Queue<LidaTask>>();
		// taskArray = tasks.toArray(new LidaTask[0]);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tasksTable = new javax.swing.JTable();
		jToolBar1 = new javax.swing.JToolBar();
		ApplyButton = new javax.swing.JButton();

		tasksTable.setModel(new TaskQueueTableModel());
		tasksTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		jScrollPane1.setViewportView(tasksTable);

		jToolBar1.setRollover(true);

		ApplyButton.setText("Refresh");
		ApplyButton.setFocusable(false);
		ApplyButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		ApplyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		ApplyButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ApplyButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(ApplyButton);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
				Short.MAX_VALUE).addComponent(jScrollPane1,
				javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jToolBar1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												269, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN
		refresh();
	}// GEN-LAST:event_ApplyButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton ApplyButton;
	private javax.swing.JTable tasksTable;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JToolBar jToolBar1;

	// End of variables declaration//GEN-END:variables

	private class TaskQueueTableModel extends AbstractTableModel {

		private static final long serialVersionUID = 1L;

		@Override
		public int getColumnCount() {
			int total = 0;
			for (Queue<LidaTask> qt : tasks.values()) {
				if (qt.size() > total)
					total = qt.size();
			}
			return total+1; //the first one is the tick number
		}

		@Override
		public int getRowCount() {
			int rows = (int) (lida.getTaskManager().getMaxTick() - LidaTaskManager
					.getCurrentTick())+1;
			return rows;
		}

		@Override
		public String getColumnName(int column) {
			String cName;
			if (column == 0) {
				cName = "tick";
			} else {
				cName = "Task " + column;
			}
			return cName;
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {
			Object o = null;
			if (columnIndex==0){
				return LidaTaskManager.getCurrentTick()+ rowIndex;
			}
			
			Queue<LidaTask> qt = tasks.get(LidaTaskManager.getCurrentTick()
					+ rowIndex);
			if (qt == null) {
				return "";
			}
			Iterator<LidaTask> it = qt.iterator();
			for (int i = 1; i <= columnIndex; i++) {
				if (it.hasNext()) {
					o = it.next();
				} else {
					o = "";
					break;
				}
			}
			return o;
		}

		@Override
		public boolean isCellEditable(int row, int column) {
			return false;
		}
	}

	@Override
	public void refresh() {
		logger.log(Level.FINEST, "Refreshing TaskQueue Panel",
				LidaTaskManager.getCurrentTick());

		display(lida.getTaskManager().getTaskQueue());
	}

	@Override
	@SuppressWarnings("unchecked")
	public void display(Object o) {
		if (o instanceof Map) {
			tasks = (Map<Long,Queue<LidaTask>>) o;

			// Concurrent Modification Exception here. 9/15/09
			// Iterating over a shared Collection during the call to 'toArray'
			((AbstractTableModel) tasksTable.getModel()).fireTableStructureChanged();
		}
	}

}
